Task2
KaroukinStanislau/KaroukinStanislau.github.io pull request #2
Opened 2017-03-26 15:36 UTC by KaroukinStanislau

2017-03-26 18:53 UTC, NikitaSedyx requested changes
js is mostly the same with @RamanKreiza
do you work together?

2017-03-26 18:53 UTC, NikitaSedyx commented on task2/index.html
> +  <script type="text/javascript" src="script.js"></script>
`./`

2017-03-26 18:53 UTC, NikitaSedyx commented on task2/script.js
> +function range() {
where are arguments?

2017-03-26 18:53 UTC, NikitaSedyx commented on task2/script.js
> +          if (i % (arguments[2]) !== 0) {
what does it do?
the third argument is step

2017-03-26 18:53 UTC, NikitaSedyx commented on task2/script.js
> +  switch (arguments.length) {
not cool switch usage, if is better here
you have mostly the same loop, why do you copy past it?

2017-03-26 18:53 UTC, NikitaSedyx commented on task2/script.js
> +    return Boolean(arr).valueOf() === true;
looks like I see the same second time
please read about filter, falsy values, type converting

2017-03-26 18:53 UTC, NikitaSedyx commented on task2/script.js
> +  arr.length = arr.length - count;
it mutates array, -1

2017-03-27 18:56 UTC, NikitaSedyx requested changes

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +  return {}.toString.call(arr) === '[object Array]'
are you sure it works?
`SyntaxError: expected expression, got '.'` is in my console

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +  if (typeof b == 'undefined') {
`b === undefined`

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +  for (var i = a; i < b; i += step) {
could you run `range(10, 20, -5)`?

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +    return element ? true : false;
why do you need it? please read about converting in conditions

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +    if (arr[i]) {
please look above and understand

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +  return arr[(arr.length - 1)];
why do you need `()`?

2017-03-27 18:56 UTC, NikitaSedyx commented on task2/script.js
> +function excludeLast(arr, count = 1) {
es6 feature

2017-03-27 19:20 UTC, KaroukinStanislau commented on task2/script.js
> +  return {}.toString.call(arr) === '[object Array]'
it works for me in chrome 56
https://learn.javascript.ru/class-instanceof
don't work in console. try "( {}.toString.call([]) )"

2017-03-27 19:26 UTC, NikitaSedyx commented on task2/script.js
> +  return {}.toString.call(arr) === '[object Array]'
I'd suggest you to use Object.prototype without any hacks

2017-03-27 20:19 UTC, KaroukinStanislau commented on task2/script.js
> +    return element ? true : false;
finally i got it :)

2017-03-28 21:01 UTC, NikitaSedyx requested changes

2017-03-28 21:01 UTC, NikitaSedyx commented on task2/script.js
> +function range(a, b, step) {
_.range(10, 2, -5) -> [10, 5]

2017-03-28 21:01 UTC, NikitaSedyx commented on task2/script.js
> +function excludeLast(arr, count) {
mostly is works

2017-03-29 19:49 UTC, NikitaSedyx approved these changes

2017-04-20 15:05 UTC, merged