binary search
KaroukinStanislau/KaroukinStanislau.github.io pull request #3
Opened 2017-04-04 10:37 UTC by KaroukinStanislau

binary search first commit

2017-04-04 12:39 UTC, NikitaSedyx requested changes

2017-04-04 12:39 UTC, NikitaSedyx commented on search/script.js
> +   var a = [0, 1, 2, 2, 3, 4, 11, 22, 69, 235, 459, 637, 789, 854];
wrong indents

2017-04-04 12:39 UTC, NikitaSedyx commented on search/script.js
> +   function recursive(array, value, left, right) {
I'd suggest to move it under search function, it's helper and it shouldn't be in global scope

2017-04-04 12:39 UTC, NikitaSedyx commented on search/script.js
> +     return recursive(array, value, 0, array.length);
btw is it possible for you to implement function without helper?

2017-04-05 13:09 UTC, NikitaSedyx requested changes

2017-04-05 13:09 UTC, NikitaSedyx commented on search/script.js
> +console.log(recursive(a, 854));
could you try to call the same but when `a = [0, 1, 2, 2, 3, 4, 11, 22, 69, 235, 459, 637];`
looks like it returns index of last element

or with `a = [];`
all calls returns 0

2017-04-05 13:47 UTC, KaroukinStanislau commented on search/script.js
> +console.log(recursive(a, 854));
yes, i forgot to fix that

2017-04-05 14:11 UTC, NikitaSedyx approved these changes

2017-04-05 14:11 UTC, NikitaSedyx commented on search/script.js
> +function recursive(array, value, left, right) {
please give another function name smth like `binarySearch`

2017-04-20 15:05 UTC, merged